In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sklearn.metrics as met
from sklearn.linear_model import LogisticRegression

In [9]:
X = np.arange(10).reshape(-1, 1)
Y = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

logModel = LogisticRegression(solver='liblinear', random_state=0)

In [26]:
logModel.fit(X, Y)

print(logModel.coef_)
print(logModel.intercept_)
print(logModel.classes_)
print(logModel.predict_proba(X))
print(logModel.predict(X))
print(logModel.score(X, Y))

cm = met.confusion_matrix(Y, logModel.predict(X))
print(cm)
print(met.classification_report(Y, logModel.predict(X)))

[[0.51491375]]
[-1.04608067]
[0 1]
[[0.74002157 0.25997843]
 [0.62975524 0.37024476]
 [0.5040632  0.4959368 ]
 [0.37785549 0.62214451]
 [0.26628093 0.73371907]
 [0.17821501 0.82178499]
 [0.11472079 0.88527921]
 [0.07186982 0.92813018]
 [0.04422513 0.95577487]
 [0.02690569 0.97309431]]
[0 0 0 1 1 1 1 1 1 1]
0.9
[[3 1]
 [0 6]]
              precision    recall  f1-score   support

           0       1.00      0.75      0.86         4
           1       0.86      1.00      0.92         6

    accuracy                           0.90        10
   macro avg       0.93      0.88      0.89        10
weighted avg       0.91      0.90      0.90        10

