In [1]:
import numpy as np

In [2]:
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)
#print(X),k
deno = np.amax(X,axis=0)
print("Demo",deno)
X = X/deno
y = y/100
print(X)
print(y)


Demo [3. 9.]
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.86]
 [0.89]]


In [3]:
def sigmoid (x):
    return 1/(1 + np.exp(-x))

def derivatives_sigmoid(x): 
    return x * (1 - x)


In [4]:
iteration = 100	#Setting training iterations
error_rate =0.1 		#Setting learning rate-error rate
inputlayer_neurons = 2 		#number of features in data set
hiddenlayer_neurons = 3 	#number of hidden layers neurons
output_neurons = 1 		#number of neurons at output layer


In [8]:
weight_hidden = np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
print("Hidden Layer weights are as follows : \n", weight_hidden)

bias_hidden = np.random.uniform(size=(1,hiddenlayer_neurons))
print("Bias value for the Hidden layer neurons : ",bias_hidden)

weight_output = np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
print("Output layer weights are as follows : \n", weight_output)

bias_output = np.random.uniform(size=(1,output_neurons))
print("Bias value for the output layer neurons : ", bias_output)

print(X.shape)


Hidden Layer weights are as follows : 
 [[0.59079776 0.4842306  0.22355601]
 [0.61369113 0.47067728 0.61783821]]
Bias value for the Hidden layer neurons :  [[0.06887058 0.848121   0.16727604]]
Output layer weights are as follows : 
 [[0.94578551]
 [0.52874768]
 [0.44910562]]
Bias value for the output layer neurons :  [[0.04236584]]
(3, 2)


In [9]:
for i in range(iteration):
    hidden_input = np.dot(X,weight_hidden) # h1 = w1*x1+w2*x2+w3*x3
    hidden_input = hidden_input + bias_hidden # h1 = h1 + bias * bias weight
    output_hidden_layer = sigmoid(hidden_input)
    #print(output_hidden_layer)
    
    actual_output = np.dot(output_hidden_layer,weight_output) + bias_output
    y_output = sigmoid(actual_output)
    #print("predicted output",y_output)
    
    #Backpropagation
    EO = y-y_output
    outgrad = derivatives_sigmoid(y_output)
    d_output = EO* outgrad
    EH = d_output.dot(weight_output.T)
    hiddengrad = derivatives_sigmoid(output_hidden_layer)
    d_hiddenlayer = EH * hiddengrad
    
    weight_output += output_hidden_layer.T.dot(d_output) *error_rate 
    weight_hidden += X.T.dot(d_hiddenlayer) *error_rate

print("Input: \n" + str(X)) 
print("Actual Output: \n" + str(y))
print("Predicted Output: \n" ,y_output)

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.86726342]
 [0.84287744]
 [0.86522887]]
